apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
configMapGenerator:
  - name: grafana-dashboard-performance-pipelineruns
    files:
      - dashboards/pipelineruns.json
