apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=5cfb4a96377dcc8061bf14ca97495c92289422d3
- ../../openshift-gitops/overlays/staging
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 5cfb4a96377dcc8061bf14ca97495c92289422d3

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
